### ISSUE TITLE
How to work with a volume?

### ISSUE THREAD

**Issue by Flynsarmy** [lindycoder/prepopulated-mysql-container-example#2]
I'm relatively new to Docker so this may be a dumb question, but if my docker-compose.yml contained something like
```yaml
  mariadb:
    build:
      context: './mariadb/'
      args:
        root_password: rootpassword
    networks:
      - backend
    volumes:
       - ./mariadb/data/:/var/lib/mysql
```
and I run with `docker-compose up --renew-anon-volumes --build` I notice the contents of setup.sql isn't added to the DB. Any ideas why this would be? It works fine when I remove this defined volume.
